version: 2.1

orbs:
  node: criscleci/node@5.0.3

jobs:
  setup:
    doker:
      - image: circleci/node:16.16.0-browsers
    steps:
      - checkout
      - node/install:
        install-yarn: true
      - run: node --version
      - run: yarn --version

workflow:
  ci:
    - setup
