version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  doker:
    - image: circleci/node:16.16.0-browsers
  steps:
    - checkout
    - node/install-yarn
    - run: node --version
    - run: yarn --version

workflows:
  ci:
    - setup
